server:
  port: ${SERVER_PORT:9084}

spring:
  profiles:
    active: @profile.active@
    group:
      docker: local
  application:
    name: macula-cloud-docs

---
# local Profile 包含 IDE 本地开发所需的全部默认配置
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    root: info
    dev.macula.cloud: debug
  file:
    name: ${user.home}/logs/${spring.application.name}/${spring.application.name}.log
